services:
    geckobot:
        build:
            context: .
        image: node:23-alpine
        restart: unless-stopped
        depends_on:
            - mysql
            - phpmyadmin
        volumes:
            - ./:/geckobot
        environment:
            MYSQL_HOST: ${HOST}
            MYSQL_USER: ${USER}
            MYSQL_PASSWORD: ${PASSWORD}
            MYSQL_DB: ${DATABASE}
            TZ: Europe/London
        env_file: .env

    mysql:
        image: mysql:9
        restart: unless-stopped
        volumes:
            - geckobot-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${PASSWORD}
            MYSQL_DATABASE: ${DATABASE}
        env_file: .env

    phpmyadmin:
        image: phpmyadmin:5-apache
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            PMA_ARBITRARY: 1

networks:
    gecko-net:
        external: true

volumes:
    geckobot-data:
        external: false
